name: flyer_chat_audio_message
version: 0.0.12+2
description: >
  Audio message package for Flutter chat apps, complementing flutter_chat_ui. #chat #ui
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_chat_ui

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_core: ^2.8.0
  just_audio: ^0.9.40
  provider: ^6.1.5
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  http: ^1.2.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
